services:

  postgres:
    container_name: postgres-spring-data
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "5050:8080"

volumes:
  postgres: