
spring:
  application:
    name: miu-assignment

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/mydb

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false

  sql:
    init:
      mode: always
  profiles:
    active: dev

server:
  port: 8080

jwt:
  secret: my-secret
